### ISSUE TITLE
[Insight] Unused method, property, variable or parameter - in src/…/Controller/EditController.php, line 70

### ISSUE THREAD

**Issue by w2pc** [ubirimi/ubirimi#21]
There is 420 examples of this, is these parts of the code really dead code? 

**[in src/Ubirimi/Calendar/Controller/EditController.php, line 70](https://github.com/ubirimi/ubirimi/blob/204014ac4be52d1f8fc7d07f8bdfde45d47a0b79/src/Ubirimi/Calendar/Controller/EditController.php#L70)**

> This `menuSelectedCategory` local variable is declared but never used. You should remove it.

```php

                return new RedirectResponse('/calendar/calendars');
            }
        }

        $menuSelectedCategory = 'calendar';
        $sectionPageTitle = $session->get('client/settings/title_name') . ' / ' . SystemProduct::SYS_PRODUCT_CALENDAR_NAME . ' / Calendar: ' . $calendar['name'] . ' / Update';

        return $this->render(__DIR__ . '/../Resources/views/Edit.php', get_defined_vars());
    }
}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/4e3d9b1a-d023-4894-a7bf-48cde810b132/analyses/12?status=violations)_

**Comment by domnulnopcea** [comment]
this is still used! in each controller this variable is set so that in the view template we know what menu to present as "selected"
