### ISSUE TITLE
Documentor spaces CSS is messed up 

### ISSUE THREAD

**Issue by w2pc** [ubirimi/ubirimi#46]
The CSS is messed up causing sections to overlap
![screen shot 2015-05-23 at 3 09 30 pm](https://cloud.githubusercontent.com/assets/885461/7785627/e66efd6c-015d-11e5-917e-c5bad1a89d20.png)

**Comment by domnulnopcea** [comment]
what browser do you use?

**Comment by w2pc** [comment]
Chrome Version 42.0.2311.152 (64-bit) OSX

**Comment by BnMcG** [comment]
This happens for me in Chrome on Linux

**Comment by domnulnopcea** [comment]
on chrome 43 debian 8 it renders perfectly! don't you have some zoom for
that page?


--
Flavius Nopcea,
CEO, Ubirimi
http://www.ubirimi.com - Fast, most affordable productivity tools

**Comment by domnulnopcea** [comment]
i can not reproduce this? do you get this bug on a fresh install of a client? from where is this SS taken?

**Comment by BnMcG** [comment]
I get the bug on the demo site and a fresh vagrant install

**Comment by w2pc** [comment]
The screenshot was taken on ubirimi production site.

**Comment by domnulnopcea** [comment]
@w2pc can you please give me the URL?
thanks

**Comment by w2pc** [comment]
https://domnuprofesor.ubirimi.net/documentador/pages/50

**Comment by Waizujin** [comment]
I am able to reproduce this as well using the Ubirimi.net site.

Steps to Reproduce
1. Login to your Ubirimi.net account.
2. Click on Documentador in the header.
3. Click on the Documentador dropdown below the logo on the top left.
4. Click on Spaces.
5. Click the Create New Space button.
6. Enter a name, and code.
7. Click Create Space.
8. You should be redirected to a spaces page that shows your space.
9. Click on the name of the space you just created.

Expected Result: Page is loaded and displays correctly.
Actual Result: Breadcrumbs are covered by the .doc-left-side element.

Video: http://screencast.com/t/J5OszD6K

Using Chrome version 42.0.2311.152 m on Windows 8.

**Comment by domnulnopcea** [comment]
thanks for the steps to reproduce this issue and the screen cast! great work!
