### ISSUE TITLE
Documentador link in secondary menu is pushed to 2 lines

### ISSUE THREAD

**Issue by Waizujin** [ubirimi/ubirimi#51]
Screenshot: http://screencast.com/t/Oj1kZtQXem8

This is being caused by the &nbsp; on line 74 of src/Ubirimi/Documentador/Resources/views/_menu.php

Browser is 42.0.2311.152 m on Windows 8.

**Comment by w2pc** [comment]
fixed in ubirimi/commit/21e854115f18f48685e286383948353b0577fcc4
